library(assertthat)
library(ricu)
library(matrixStats)
library(flextable)
root <- rprojroot::find_root(".git/index")
r_dir <- file.path(root, "r")
invisible(lapply(list.files(r_dir, full.names = TRUE), source))

dose <- vec_score(config("dose"))
save_as_docx(score2table(dose), path = file.path(root, "tables", "Table2.docx"))
