
library(ricu)
library(ggplot2)
library(assertthat)
library(data.table)
library(mgcv)
library(matrixStats)
library(CalibrationCurves)
library(precrec)
library(magrittr)
library(cowplot)
library(officer)
library(parallel)
library(flextable)
library(stringr)

Sys.setenv(SCORE_NAME = "Sepsis SOFA")
